### ISSUE TITLE
Hello from Flare

### ISSUE THREAD

**Issue by aviau** [mizzled/comitigation#1]
Hey!

[We](https://flare.io/) run a cybersec SaaS and we analyze everything that is commited on GitHub.

Let's just say that we noticed you ;)

**Comment by mizzled** [comment]
Hi!
are you some github support guys request me to cease my project?
im gland you choosed the passive method !

**Comment by mizzled** [comment]
im leaving the issue open to read your reply,
in case of a request i would stop

**Comment by aviau** [comment]
No we are not GitHub support. Just a private company analyzing public commits on GitHub. You can continue :)

**Comment by mizzled** [comment]
Oh, alright xD
